# Generated by Django 5.2.16 on 2026-09-02 06:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('penyewaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengembalian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengembalian', models.DateField(verbose_name='Tanggal pengembalian')),
                ('kondisi_alat', models.CharField(choices=[('baik', 'Baik'), ('rusak_ringan', 'Rusak Ringan'), ('rusak_berat', 'Rusak Berat'), ('hilang', 'Hilang')], max_length=15, verbose_name='Kondisi alat')),
                ('keterlambatan', models.PositiveIntegerField(default=0, editable=False, verbose_name='Keterlambatan (hari)')),
                ('denda_keterlambatan', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='Denda keterlambatan (Rp)')),
                ('catatan_kerusakan', models.TextField(blank=True, verbose_name='Catatan kerusakan')),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('penyewaan', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pengembalian', to='penyewaan.penyewaan', verbose_name='Penyewaan terkait')),
            ],
            options={
                'verbose_name': 'Pengembalian',
                'verbose_name_plural': 'Data Pengembalian',
                'ordering': ['-dicatat_pada'],
            },
        ),
    ]
