# Generated by Django 5.2.16 on 2026-09-02 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_alat', models.CharField(max_length=100, verbose_name='Nama alat')),
                ('jenis_alat', models.CharField(choices=[('kamera', 'Kamera'), ('lensa', 'Lensa'), ('lighting', 'Lighting'), ('audio', 'Audio'), ('tripod', 'Tripod / Stabilizer'), ('drone', 'Drone'), ('lainnya', 'Lainnya')], max_length=20, verbose_name='Jenis alat')),
                ('nomor_inventaris', models.CharField(max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='Format nomor inventaris tidak valid. Contoh yang benar: KM-0001, DR-00023.', regex='^[A-Z]{2,5}-\\d{3,6}$')], verbose_name='Nomor inventaris')),
                ('tahun_pembelian', models.PositiveIntegerField(verbose_name='Tahun pembelian')),
                ('warna', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(message='Warna hanya boleh berisi huruf dan spasi, contoh: Hitam, Silver, Abu-abu Tua.', regex='^[A-Za-z\\s]+$')], verbose_name='Warna')),
                ('harga_sewa_per_hari', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1000, 'Harga sewa minimal Rp1.000 per hari.')], verbose_name='Harga sewa per hari (Rp)')),
                ('status_alat', models.CharField(choices=[('tersedia', 'Tersedia'), ('disewa', 'Disewa'), ('rusak', 'Rusak'), ('maintenance', 'Dalam Perbaikan')], default='tersedia', max_length=15, verbose_name='Status alat')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Alat',
                'verbose_name_plural': 'Data Alat',
                'ordering': ['nama_alat'],
            },
        ),
    ]
