# Generated by Django 5.2.16 on 2026-09-02 06:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('penyewaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_pembayaran', models.CharField(choices=[('tunai', 'Tunai'), ('transfer', 'Transfer Bank'), ('kartu', 'Kartu Debit/Kredit'), ('ewallet', 'E-Wallet')], max_length=10, verbose_name='Metode pembayaran')),
                ('jumlah_pembayaran', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(1, 'Jumlah pembayaran harus lebih besar dari 0.')], verbose_name='Jumlah pembayaran (Rp)')),
                ('tanggal_pembayaran', models.DateField(verbose_name='Tanggal pembayaran')),
                ('status_pembayaran', models.CharField(choices=[('pending', 'Pending'), ('lunas', 'Lunas'), ('gagal', 'Gagal')], default='pending', max_length=10, verbose_name='Status pembayaran')),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('penyewaan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pembayaran_set', to='penyewaan.penyewaan', verbose_name='Penyewaan terkait')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Data Pembayaran',
                'ordering': ['-dicatat_pada'],
            },
        ),
    ]
