# Generated by Django 5.2.16 on 2026-09-02 06:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Penyewaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penyewa', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Nama penyewa hanya boleh berisi huruf, spasi, titik, apostrof, dan tanda hubung.', regex="^[A-Za-z\\s.'\\-]+$")], verbose_name='Nama penyewa')),
                ('no_telepon_penyewa', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Nomor telepon harus format Indonesia yang valid, contoh: 081234567890 atau +6281234567890.', regex='^(\\+62|62|0)8[1-9][0-9]{6,10}$')], verbose_name='Nomor telepon penyewa')),
                ('tanggal_sewa', models.DateField(verbose_name='Tanggal sewa')),
                ('tanggal_pengembalian_rencana', models.DateField(verbose_name='Tanggal pengembalian (rencana)')),
                ('lama_penyewaan', models.PositiveIntegerField(default=0, editable=False, verbose_name='Lama penyewaan (hari)')),
                ('total_biaya', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=12, verbose_name='Total biaya (Rp)')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('alat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='penyewaan_set', to='alat.alat', verbose_name='Alat yang disewa')),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penyewaan_dibuat', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Penyewaan',
                'verbose_name_plural': 'Data Penyewaan',
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
